---
branches:
  - main
  - beta

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - "@terrestris/maven-semantic-release"